version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: pgserver
        volumes:
            - ./postgres:/var/lib/postgresql/data
        env_file:
            - .env
        restart: on-failure
        ports:
             - 5432:5432

    server:
        build: .
        container_name: python_server
        volumes:
            - .:/server
        restart: on-failure
        ports: 
            - 5000:5000
        depends_on:
            - postgres
        command: >
            bash -c 'while !</dev/tcp/postgres/5432;
            do sleep 1;
            done;
            export FLASK_APP=webapp
            && flask db upgrade
            && export FLASK_ENV=development
            && flask run --host 0.0.0.0'
