"""added yeasts enum

Revision ID: 0ccfc8f311a2
Revises: 81fcb52022a2
Create Date: 2022-10-18 07:49:47.067043

"""
from alembic import op
import sqlalchemy as sa
from webapp.yeasts.enums import TypeOfYeast


# revision identifiers, used by Alembic.
revision = '0ccfc8f311a2'
down_revision = '81fcb52022a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yeasts', 'name')
    type_of_yeast = sa.Enum(TypeOfYeast, name="typeofyeast")
    type_of_yeast.create(op.get_bind(), checkfirst=True)
    op.add_column('yeasts', sa.Column('name', sa.Enum('wb_06', 'k_97', 'w_34_70', 'maxifarm', name='typeofyeast'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE yeasts_typeofyeast_enum;")
    # ### end Alembic commands ###
