"""added yeasts enum

Revision ID: 0ccfc8f311a2
Revises: 81fcb52022a2
Create Date: 2022-10-18 07:49:47.067043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccfc8f311a2'
down_revision = '81fcb52022a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yeasts', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('wb_06', 'k_97', 'w_34_70', 'maxifarm', name='type_of_yeast'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yeasts', 'name',
               existing_type=sa.Enum('wb_06', 'k_97', 'w_34_70', 'maxifarm', name='type_of_yeast'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
