"""upgade Tank models

Revision ID: 43bd1372c837
Revises: a3708983800d
Create Date: 2022-10-06 21:08:03.767668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bd1372c837'
down_revision = 'a3708983800d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tank', sa.Column('brew_number_first', sa.Integer(), nullable=False))
    op.add_column('tank', sa.Column('brew_number_last', sa.Integer(), nullable=False))
    op.drop_column('tank', 'brew_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tank', sa.Column('brew_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tank', 'brew_number_last')
    op.drop_column('tank', 'brew_number_first')
    # ### end Alembic commands ###
