"""merge main

Revision ID: 6b7d7e96ddad
Revises: 6cba287ccbc0
Create Date: 2022-10-05 22:15:12.069454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7d7e96ddad'
down_revision = '6cba287ccbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('kellerbier', 'dunkelbier', 'bropils', 'wheatbeer', 'traditional_dark', 'traditional_light', 'traditional_wheat', 'cider', name='titlebeer'), nullable=False),
    sa.Column('actual_volume', sa.Integer(), nullable=True),
    sa.Column('beer_grooving', sa.Boolean(), nullable=True),
    sa.Column('cooling', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('measuring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tank_id'], ['tank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measuring_tank_id'), 'measuring', ['tank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measuring_tank_id'), table_name='measuring')
    op.drop_table('measuring')
    op.drop_table('tank')
    # ### end Alembic commands ###
