"""upgade Tank models

Revision ID: a3708983800d
Revises: 5ce7815d2195
Create Date: 2022-10-06 20:49:27.962255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3708983800d'
down_revision = '5ce7815d2195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tank', sa.Column('brew_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tank', 'brew_number')
    # ### end Alembic commands ###
