"""Tank model

Revision ID: a3eb6568eff7
Revises: a2211af39132
Create Date: 2022-10-02 19:58:19.790351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3eb6568eff7'
down_revision = 'a2211af39132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tank', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tank', type_='unique')
    # ### end Alembic commands ###
